"""The router's third blind set (blind #3): written last, after the rules had been tuned on DEV, TEST and TEST2, to measure them
on words they never saw. It was measured once, on the first pass and before any change to the rules (bench/router_blind.py
prints that run); whatever was fixed afterwards is reported as such in docs/bench/menti_2026-09-30.md. Same format and channel
states as router_set.py."""
from __future__ import annotations

from .router_set import Item, _mk

B = _mk("test3")

TEST3: list[Item] = [
    # ---- Italian, typed, channel open and quiet: the Captain fights the battle with the bridge
    B("mira ai motori del cocytus", "it", "typed", "enemy", "crew"),
    B("voglio un rapporto sugli scudi", "it", "typed", "enemy", "crew"),
    B("quanti caccia abbiamo in volo", "it", "typed", "enemy", "crew"),
    B("dite ai piloti di rientrare", "it", "typed", "enemy", "crew"),
    B("riparate il ponte tre", "it", "typed", "enemy", "crew"),
    B("dov e l altra nave", "it", "typed", "enemy", "crew"),
    B("accostiamo a sinistra", "it", "typed", "enemy", "crew"),
    B("caricate i railgun", "it", "typed", "enemy", "crew"),
    B("fuoxo sul cocytis", "it", "typed", "enemy", "crew"),
    B("sganciate i missili", "it", "typed", "enemy", "crew"),
    B("qualcuno mi dice cosa sta succedendo", "it", "typed", "enemy", "crew"),
    B("richiamate i droni", "it", "typed", "enemy", "crew"),
    B("dammi uno schermo tattico", "it", "typed", "enemy", "crew"),
    B("comunicazioni apri un canale con l ammiraglio", "it", "typed", "enemy", "crew"),
    B("cosa dice la flotta", "it", "typed", "enemy", "crew"),
    B("portaci dietro l asteroide", "it", "typed", "enemy", "crew"),
    B("quanto e grande il cocytus", "it", "typed", "enemy", "crew"),
    B("ci sono feriti", "it", "typed", "enemy", "crew"),
    B("portate i feriti in infermeria", "it", "typed", "enemy", "crew"),
    B("i sensori vedono altre navi", "it", "typed", "enemy", "crew"),
    B("che intenzioni ha quella nave secondo te", "it", "typed", "enemy", "crew", hard=True),
    B("siamo pronti a saltare", "it", "typed", "enemy", "crew", hard=True),
    B("che cosa fate", "it", "typed", "enemy", "crew", hard=True),
    B("adesso basta", "it", "typed", "enemy", "crew", hard=True),
    # ---- Italian, typed, to the enemy captain (no name, or with it): demands, offers, threats, questions
    B("cocytus fermatevi subito", "it", "typed", "enemy", "external"),
    B("vael ti conviene ascoltarmi", "it", "typed", "enemy", "external"),
    B("avete dieci secondi per arrendervi", "it", "typed", "enemy", "external"),
    B("non voglio combattere vael", "it", "typed", "enemy", "external"),
    B("che cosa cercate qui", "it", "typed", "enemy", "external"),
    B("spegnete le armi e parliamo", "it", "typed", "enemy", "external"),
    B("vi do la mia parola", "it", "typed", "enemy", "external"),
    B("sei sola vael", "it", "typed", "enemy", "external"),
    B("rispondimi capitano", "it", "typed", "enemy", "external"),
    B("non ci sono altre strade per voi", "it", "typed", "enemy", "external"),
    B("andatevene subito", "it", "typed", "enemy", "external"),
    B("questa e casa nostra lasciateci in pace", "it", "typed", "enemy", "external"),
    B("non ce la farete", "it", "typed", "enemy", "external"),
    B("restate dove siete", "it", "typed", "enemy", "external", hard=True),
    # ---- Italian, spoken (the recogniser's punctuation and capitals), channel open and quiet
    B("Ferryman, sono il Capitano dell'Aquila. Cosa vuole da noi?", "it", "spoken", "enemy", "external"),
    B("Vael, non siamo nemici. Possiamo trovare un accordo.", "it", "spoken", "enemy", "external"),
    B("Ferryman, le do cinque minuti. Dopo, apriremo il fuoco.", "it", "spoken", "enemy", "external"),
    B("Non ci arrendiamo, Ferryman. Lo dica ai suoi.", "it", "spoken", "enemy", "external"),
    B("Vael, ho letto il suo messaggio, ma la risposta è no.", "it", "spoken", "enemy", "external"),
    B("Ehm, Voss, tieni pronti i missili e non sparare finché non te lo dico.", "it", "spoken", "enemy", "crew"),
    B("Ferri, tienici lontani dal fuoco del Cocytus.", "it", "spoken", "enemy", "crew"),
    B("Nair, qualcosa di nuovo sui sensori?", "it", "spoken", "enemy", "crew"),
    B("Serra, cosa ne pensa? Le crede?", "it", "spoken", "enemy", "crew"),
    B("Tanaka, metti la Vael sullo schermo grande.", "it", "spoken", "enemy", "crew"),
    B("Il Ferryman ha detto una cosa interessante, Serra. Tu che ne dici?", "it", "spoken", "enemy", "crew"),
    B("Comunicazioni, dica alla signora Vael che ci ritiriamo.", "it", "spoken", "enemy", "crew"),
    B("Allora, riassumiamo: il Cocytus è solo, giusto?", "it", "spoken", "enemy", "crew"),
    B("Va bene, Vael. Accetto. Voss, sospendi il fuoco.", "it", "spoken", "enemy", "both", ext="accetto", crew="sospendi il fuoco"),
    B("Non mi fido di lei, Vael. Ferri, allontanaci.", "it", "spoken", "enemy", "both", ext="non mi fido", crew="allontanaci"),
    B("Ferryman, ultimo avvertimento. Voss, armi pronte.", "it", "spoken", "enemy", "both", ext="ultimo avvertimento", crew="armi pronte"),
    B("Vael, aspetti un momento. Ferri, riduci la velocità.", "it", "spoken", "enemy", "both", ext="momento", crew="riduci la velocita"),
    B("Un attimo Vael. Comunicazioni, registrate tutto.", "it", "spoken", "enemy", "both", ext="attimo", crew="registrate tutto"),
    # ---- Italian, an exchange going on (she just spoke)
    B("va bene", "it", "typed", "live", "external", hard=True),
    B("non se ne parla", "it", "typed", "live", "external"),
    B("cosa proponi", "it", "typed", "live", "external"),
    B("quanto tempo mi dai", "it", "typed", "live", "external"),
    B("si ma voi ritirate le navi", "it", "typed", "live", "external"),
    B("Voss, cosa ne pensi di quello che ha detto?", "it", "spoken", "live", "crew"),
    B("Serra, ha ragione lei?", "it", "spoken", "live", "crew"),
    B("quanto ci resta prima che entrino in portata", "it", "typed", "live", "crew"),
    B("Comunicazioni, chiudete il canale.", "it", "spoken", "live", "crew"),
    B("Lo so, Vael. Mi lasci un momento per pensarci.", "it", "spoken", "live", "external"),
    # ---- English, typed, channel open and quiet
    B("how many missiles do we have left", "en", "typed", "enemy", "crew"),
    B("show me the enemy fleet on screen", "en", "typed", "enemy", "crew"),
    B("shields to the front", "en", "typed", "enemy", "crew"),
    B("any hull breaches", "en", "typed", "enemy", "crew"),
    B("hit their engines", "en", "typed", "enemy", "crew"),
    B("where did the second ship go", "en", "typed", "enemy", "crew"),
    B("tell the fighters to hold position", "en", "typed", "enemy", "crew"),
    B("give me the damage report", "en", "typed", "enemy", "crew"),
    B("what does the fleet say", "en", "typed", "enemy", "crew"),
    B("ready the railguns", "en", "typed", "enemy", "crew"),
    B("someone tell me what is happening", "en", "typed", "enemy", "crew"),
    B("keep us behind the asteroid", "en", "typed", "enemy", "crew"),
    B("back off vael", "en", "typed", "enemy", "external"),
    B("you have thirty seconds to stand down", "en", "typed", "enemy", "external"),
    B("we can settle this without a fight", "en", "typed", "enemy", "external"),
    B("why are you here", "en", "typed", "enemy", "external"),
    B("you will not get past us", "en", "typed", "enemy", "external"),
    B("lower your weapons and we talk", "en", "typed", "enemy", "external"),
    B("we dont want a war", "en", "typed", "enemy", "external"),
    B("i am giving you one chance", "en", "typed", "enemy", "external"),
    B("answer me ferryman", "en", "typed", "enemy", "external"),
    B("cut your engines", "en", "typed", "enemy", "external"),
    # ---- English, spoken
    B("Vael, I know you're listening. Let's talk.", "en", "spoken", "enemy", "external"),
    B("Ferryman, you have my word: withdraw and nobody dies today.", "en", "spoken", "enemy", "external"),
    B("You are outgunned, Ferryman, and you know it.", "en", "spoken", "enemy", "external"),
    B("Voss, fire the moment they cross ten kilometres.", "en", "spoken", "enemy", "crew"),
    B("Helm, bring us to zero-nine-zero and hold.", "en", "spoken", "enemy", "crew"),
    B("Serra, do you trust her?", "en", "spoken", "enemy", "crew"),
    B("Ops, put her on the main screen, then open a channel to the fleet.", "en", "spoken", "enemy", "crew"),
    B("Nair, what's her ship's power output?", "en", "spoken", "enemy", "crew"),
    B("All right, Vael, I'll hear your terms. Tactical, hold fire.", "en", "spoken", "enemy", "both", ext="hear your terms", crew="hold fire"),
    B("Ferryman, I'll consider it. Serra, thoughts?", "en", "spoken", "enemy", "both", ext="consider it", crew="thoughts"),
    B("I hear you, Vael. Give me a moment.", "en", "spoken", "live", "external"),
    B("wait what did she say", "en", "typed", "live", "crew", hard=True),
    B("Comms, mute the channel.", "en", "spoken", "live", "crew"),
    B("Ferryman, you have my word.", "en", "spoken", "live", "external"),
    # ---- Spanish
    B("cuantos misiles quedan", "es", "typed", "enemy", "crew"),
    B("que salgan los cazas", "es", "typed", "enemy", "crew"),
    B("abran fuego", "es", "typed", "enemy", "crew"),
    B("Timonel, rumbo cero nueve cero.", "es", "spoken", "enemy", "crew"),
    B("Voss, apunta a los motores.", "es", "spoken", "enemy", "crew"),
    B("¿Qué dice la flota?", "es", "spoken", "enemy", "crew"),
    B("Detengan sus motores, Ferryman.", "es", "spoken", "enemy", "external"),
    B("no queremos guerra vael", "es", "typed", "enemy", "external"),
    B("les doy una oportunidad", "es", "typed", "enemy", "external"),
    B("digame que quiere", "es", "typed", "live", "external"),
    B("Retírense ahora o abriremos fuego.", "es", "spoken", "enemy", "external"),
    B("Vael, escúcheme.", "es", "spoken", "enemy", "external"),
    B("Déjeme pensarlo, Vael. Voss, mantenga la guardia.", "es", "spoken", "enemy", "both", ext="pensarlo", crew="mantenga la guardia"),
    # ---- French
    B("combien de missiles il nous reste", "fr", "typed", "enemy", "crew"),
    B("rapport des dégâts", "fr", "typed", "enemy", "crew"),
    B("mettez-les sur l'écran principal", "fr", "typed", "enemy", "crew"),
    B("Tactique, verrouillez le Cocytus.", "fr", "spoken", "enemy", "crew"),
    B("Serra, qu'en pensez-vous ?", "fr", "spoken", "enemy", "crew"),
    B("Ferryman, coupez vos moteurs.", "fr", "spoken", "enemy", "external"),
    B("nous ne voulons pas la guerre", "fr", "typed", "enemy", "external"),
    B("vous n'avez aucune chance", "fr", "typed", "enemy", "external"),
    B("répondez-moi Vael", "fr", "typed", "enemy", "external"),
    B("Cocytus, ici le capitaine. Baissez vos armes.", "fr", "spoken", "enemy", "external"),
    # ---- German
    B("wie viele Raketen haben wir noch", "de", "typed", "enemy", "crew"),
    B("Schadensbericht bitte", "de", "typed", "enemy", "crew"),
    B("Voss, feuern Sie auf die Triebwerke.", "de", "spoken", "enemy", "crew"),
    B("Ferri, bringen Sie uns hinter den Asteroiden.", "de", "spoken", "enemy", "crew"),
    B("Öffnet einen Kanal zur Flotte.", "de", "spoken", "enemy", "crew"),
    B("Ferryman, ziehen Sie sich zurück.", "de", "spoken", "enemy", "external"),
    B("wir wollen keinen Krieg", "de", "typed", "enemy", "external"),
    B("Sie haben keine Chance, Vael.", "de", "spoken", "enemy", "external"),
    B("antworten Sie mir", "de", "typed", "live", "external"),
    B("Was wollen Sie von uns?", "de", "spoken", "enemy", "external"),
    B("Wir hören zu, Ferryman. Voss, Waffen bereit.", "de", "spoken", "enemy", "both", ext="wir horen zu", crew="waffen bereit"),
    # ---- the fleet channel (Vice Admiral Rourke): what is for him and what is for the bridge
    B("Ammiraglio, abbiamo tre nemici in avvicinamento, chiediamo supporto.", "it", "spoken", "fleet", "external"),
    B("rourke copritemi il fianco sinistro", "it", "typed", "fleet", "external"),
    B("Admiral, we've lost our port shields, requesting cover.", "en", "spoken", "fleet", "external"),
    B("Amiral, nous sommes sous le feu ennemi.", "fr", "spoken", "fleet", "external"),
    B("Admiral, wir brauchen Verstärkung.", "de", "spoken", "fleet", "external"),
    B("Almirante, necesitamos apoyo.", "es", "spoken", "fleet", "external"),
    B("Voss, fuoco sul più vicino.", "it", "typed", "fleet", "crew"),
    B("Ferri, tienici dietro il Praetorian.", "it", "spoken", "fleet", "crew"),
    B("Roger that, Admiral. We'll hold the line.", "en", "spoken", "fleet_live", "external"),
    B("Comunicazioni, cosa vuole l'ammiraglio?", "it", "spoken", "fleet_live", "crew"),
    B("Ammiraglio, ricevuto. Ferri, virate a dritta.", "it", "spoken", "fleet_live", "both", ext="ricevuto", crew="virate a dritta"),
    # ---- muted (nothing the Captain says goes out) and no channel: everything stays on the bridge
    B("vael arrendetevi ora", "it", "typed", "muted", "crew"),
    B("Ferryman, ritiri le navi.", "it", "spoken", "muted", "crew"),
    B("Vael, stand down or we fire.", "en", "spoken", "muted", "crew"),
    B("Ferryman Vael, mi sente?", "it", "spoken", "none", "crew"),
    B("cocytus arrendetevi", "it", "typed", "none", "crew"),
    B("Vael, this is your last warning.", "en", "spoken", "none", "crew"),
    B("Tanaka, apri un canale con il Cocytus.", "it", "spoken", "none", "crew"),
    # ---- where he is looking
    B("cosa volete da noi", "it", "typed", "enemy", "external", facing="viewscreen"),
    B("fuoco", "it", "typed", "enemy", "crew", facing="viewscreen"),
    B("quanti missili", "it", "typed", "enemy", "crew", facing="tactical"),
    B("piu veloce", "it", "typed", "enemy", "crew", facing="helm"),
]
