"""The router's second blind set: written after the first blind set (router_test_set.py) had been read and its errors fixed, so
that the number reported at the end is measured on words the rules never saw. Same format and channel states."""
from __future__ import annotations

from .router_set import Item, _mk

B = _mk("test2")

TEST2: list[Item] = [
    # ---- to the bridge, with the channel open: barks, questions, talk about the enemy in the third person
    B("fuoco!", "it", "typed", "enemy", "crew"),
    B("sparate!", "it", "spoken", "enemy", "crew"),
    B("feuer!", "de", "typed", "enemy", "crew"),
    B("fuego!", "es", "typed", "enemy", "crew"),
    B("feu!", "fr", "typed", "enemy", "crew"),
    B("vael sta bluffando", "it", "typed", "enemy", "crew", hard=True),
    B("Vael sta bluffando, Voss. Non abbassare la guardia.", "it", "spoken", "enemy", "crew"),
    B("il cocytus e fuori portata voss", "it", "typed", "enemy", "crew"),
    B("Vael is bluffing, Voss.", "en", "spoken", "enemy", "crew"),
    B("l'aquila regge", "it", "typed", "enemy", "crew", hard=True),
    B("Ferrari rotta due sette zero", "it", "typed", "enemy", "crew"),
    B("Comandante Serra, rapporto sulla situazione.", "it", "spoken", "enemy", "crew"),
    B("Serra, cosa consigli?", "it", "spoken", "enemy", "crew"),
    B("Ferri, portaci vicino al Cocytus, ma non troppo.", "it", "spoken", "enemy", "crew"),
    B("Ferryman Vael ha perso il suo ammiraglio, Serra. Sfruttiamolo.", "it", "spoken", "enemy", "crew"),
    B("che nervi", "it", "typed", "enemy", "crew", hard=True),
    B("ok ci ritiriamo", "it", "typed", "enemy", "crew"),
    B("ritirata verso il gate", "it", "typed", "enemy", "crew"),
    B("ritiriamoci", "it", "typed", "enemy", "crew"),
    B("attenzione missili in arrivo", "it", "typed", "enemy", "crew"),
    B("tutti ai posti di combattimento", "it", "typed", "enemy", "crew"),
    B("abbiamo perso i sensori", "it", "typed", "enemy", "crew"),
    B("fire at will", "en", "spoken", "enemy", "crew"),
    B("what's the range to the Cocytus?", "en", "spoken", "enemy", "crew"),
    B("Ops, how long until the reactor is back?", "en", "spoken", "enemy", "crew"),
    B("Okonkwo, I need more power to the forward shields.", "en", "spoken", "enemy", "crew"),
    B("Lindqvist, how many wounded?", "en", "spoken", "enemy", "crew"),
    B("can we outrun them", "en", "typed", "enemy", "crew"),
    B("get the fighters out", "en", "typed", "enemy", "crew"),
    B("Price, scramble Alpha.", "en", "spoken", "enemy", "crew"),
    B("¿Podemos alcanzarlos?", "es", "spoken", "enemy", "crew"),
    B("Ferri, acércanos a diez kilómetros.", "es", "spoken", "enemy", "crew"),
    B("cuantos misiles nos quedan", "es", "typed", "live", "crew"),
    B("Timonier, tenez la distance.", "fr", "spoken", "enemy", "crew"),
    B("Peut-on les rattraper ?", "fr", "spoken", "enemy", "crew"),
    B("Steuermann, halten Sie die Entfernung.", "de", "spoken", "enemy", "crew"),
    B("Können wir sie einholen?", "de", "spoken", "enemy", "crew"),
    B("Nair, wie stark sind ihre Schilde?", "de", "spoken", "enemy", "crew"),
    # ---- to the enemy: demands, threats, offers, pleas, in different words
    B("arrenditi cocytus", "it", "typed", "enemy", "external"),
    B("Si fermi, Ferryman.", "it", "spoken", "enemy", "external"),
    B("Ferryman Vael, la invito a spegnere i motori.", "it", "spoken", "enemy", "external"),
    B("Vael, le sue navi sono circondate. Non ha scampo.", "it", "spoken", "enemy", "external"),
    B("nessuno deve morire oggi vael", "it", "typed", "enemy", "external"),
    B("vi do la possibilita di andarvene", "it", "typed", "enemy", "external"),
    B("se aprite il fuoco vi spazzo via", "it", "typed", "enemy", "external"),
    B("Ferryman, sono disposto a ascoltare le vostre ragioni.", "it", "spoken", "enemy", "external"),
    B("Lasciate andare il Brightwater e vi lascerò ritirare.", "it", "spoken", "enemy", "external"),
    B("che cosa ci fate qui", "it", "typed", "enemy", "external"),
    B("perche non rispondete", "it", "typed", "enemy", "external"),
    B("rispondete cocytus", "it", "typed", "enemy", "external"),
    B("ferryman non fatelo", "it", "typed", "enemy", "external"),
    B("Cocytus, this is your final warning.", "en", "spoken", "enemy", "external"),
    B("Ferryman, I know you don't want this fight any more than I do.", "en", "spoken", "enemy", "external"),
    B("let us pass and no one gets hurt", "en", "typed", "enemy", "external"),
    B("vael respond", "en", "typed", "enemy", "external"),
    B("you are surrounded", "en", "typed", "enemy", "external"),
    B("what are your intentions", "en", "typed", "enemy", "external"),
    B("if you fire that missile there will be no negotiation", "en", "typed", "enemy", "external"),
    B("Commander, I'm giving you sixty seconds to stand down.", "en", "spoken", "enemy", "external"),
    B("Vael, your crew doesn't have to die for this.", "en", "spoken", "enemy", "external"),
    B("Rindanse y les garantizo un trato digno.", "es", "spoken", "enemy", "external"),
    B("ferryman no dispare", "es", "typed", "enemy", "external"),
    B("Ferryman, ¿qué es lo que quieren realmente?", "es", "spoken", "enemy", "external"),
    B("Vael, écoutez-moi. Personne n'a besoin de mourir.", "fr", "spoken", "enemy", "external"),
    B("rendez vous ferryman", "fr", "typed", "enemy", "external"),
    B("Ferryman, qu'est-ce que vous voulez vraiment ?", "fr", "spoken", "enemy", "external"),
    B("Vael, niemand muss heute sterben.", "de", "spoken", "enemy", "external"),
    B("ergebt euch ferryman", "de", "typed", "enemy", "external"),
    B("Ferryman, was wollen Sie wirklich?", "de", "spoken", "enemy", "external"),
    # ---- the exchange is going on
    B("scusa?", "it", "typed", "live", "external", hard=True),
    B("continui", "it", "typed", "live", "external"),
    B("e se rifiuto", "it", "typed", "live", "external"),
    B("ho capito. Datemi un momento per pensarci.", "it", "spoken", "live", "external"),
    B("Voss, hai sentito? Dimmi se è credibile.", "it", "spoken", "live", "crew"),
    B("tenete le armi calde ma non sparate", "it", "typed", "live", "crew"),
    B("Ferri, resta dove sei.", "it", "spoken", "live", "crew"),
    B("go on", "en", "typed", "live", "external"),
    B("and if I refuse?", "en", "spoken", "live", "external"),
    B("I need a moment to think it over.", "en", "spoken", "live", "external"),
    B("Serra, is she telling the truth?", "en", "spoken", "live", "crew"),
    B("weapons hot but hold fire", "en", "typed", "live", "crew"),
    B("Acepto. Pero primero retiren sus cazas.", "es", "spoken", "live", "external"),
    B("J'accepte, mais retirez d'abord vos chasseurs.", "fr", "spoken", "live", "external"),
    B("Einverstanden, aber zuerst ziehen Sie Ihre Jäger ab.", "de", "spoken", "live", "external"),
    # ---- both
    B("Vael, ha un minuto. Voss, missili pronti.", "it", "spoken", "enemy", "both", ext="un minuto", crew="missili pronti"),
    B("Vael, one minute. Tactical, prepare a full salvo.", "en", "spoken", "enemy", "both", ext="one minute", crew="full salvo"),
    B("Ferryman, ich gebe Ihnen eine Minute. Taktik, Raketen bereit.", "de", "spoken", "enemy", "both", ext="minute", crew="raketen"),
    # ---- no channel, muted
    B("arrenditi cocytus", "it", "typed", "none", "crew"),
    B("Vael, respond.", "en", "spoken", "none", "crew"),
    B("ferryman rindase", "es", "typed", "none", "crew"),
    B("Ferryman, rendez-vous.", "fr", "spoken", "muted", "crew"),
    B("Ferryman, ergeben Sie sich.", "de", "spoken", "muted", "crew"),
    B("cessate il fuoco vael", "it", "typed", "muted", "crew"),
    # ---- the fleet
    B("ammiraglio ci serve copertura sul fianco sinistro", "it", "typed", "fleet", "external"),
    B("Vigilant, coprite la nostra poppa.", "it", "spoken", "fleet", "external"),
    B("Rourke, qui Aquila, chiediamo istruzioni.", "it", "spoken", "fleet", "external"),
    B("Martin, cosa risponde la flotta?", "it", "spoken", "fleet_live", "crew"),
    B("Admiral, we hold the line. Requesting reinforcements.", "en", "spoken", "fleet", "external"),
    B("Comms, tell the fleet we need cover.", "en", "spoken", "fleet", "crew"),
    B("Almirante, solicito refuerzos de inmediato.", "es", "spoken", "fleet", "external"),
    B("Amiral, nous tenons la ligne.", "fr", "spoken", "fleet", "external"),
    B("Admiral, wir halten die Stellung.", "de", "spoken", "fleet", "external"),
    # ---- who the Captain faces
    B("resisti", "it", "typed", "enemy", "crew", facing="engineering"),
    B("più veloce", "it", "typed", "enemy", "crew", facing="helm"),
    B("cosa volete davvero", "it", "typed", "live", "external", facing="viewscreen"),
    B("faster", "en", "typed", "enemy", "crew", facing="helm"),
]
