"""The router's fourth blind set (blind #4): written after the lessons of the third set had been built into the rules and the model's
prompt, from a different angle (a boarding, hostages, a bargain, allied ships, mistakes of the speech recogniser in the officers'
names, Italian mixed with English, long spoken sentences with hesitations). Measured once, on the first pass and before any change
(bench/router_blind.py --set test4); nothing was tuned on it. Same format and channel states as router_set.py."""
from __future__ import annotations

from .router_set import Item, _mk

B = _mk("test4")

TEST4: list[Item] = [
    # ---- the recogniser mangles the names ("Boss" for Voss, "Ferry" for Ferri, "Nero" for Nair): still the bridge
    B("Boss, fuoco a volontà.", "it", "spoken", "enemy", "crew"),
    B("Ferry, portaci fuori di qui.", "it", "spoken", "enemy", "crew"),
    B("Nero, che cosa vedi sui sensori?", "it", "spoken", "enemy", "crew"),
    B("Boss, fire at will.", "en", "spoken", "enemy", "crew"),
    B("Ferry, hard to port.", "en", "spoken", "enemy", "crew"),
    B("Tanaca, mostrami la flotta nemica.", "it", "spoken", "enemy", "crew"),
    B("Sera, dammi un consiglio.", "it", "spoken", "enemy", "crew"),
    B("Vos, missili pronti.", "it", "spoken", "enemy", "crew"),
    # ---- Italian mixed with English, the way players talk
    B("lock target sul cocytus", "it", "typed", "enemy", "crew"),
    B("shields al massimo", "it", "typed", "enemy", "crew"),
    B("fire!", "it", "typed", "enemy", "crew"),
    B("missili, fire", "it", "typed", "enemy", "crew"),
    B("red alert e tutti ai posti", "it", "typed", "enemy", "crew"),
    B("railgun ready?", "it", "typed", "enemy", "crew"),
    B("dammi un boarding party pronto al portello", "it", "typed", "enemy", "crew"),
    B("ok ragazzi facciamolo", "it", "typed", "enemy", "crew", hard=True),
    # ---- a boarding and hostages (the Brightwater): orders to the bridge with the channel open
    B("preparate la squadra d'abbordaggio", "it", "typed", "enemy", "crew"),
    B("quanti uomini abbiamo sul ponte due", "it", "typed", "enemy", "crew"),
    B("isolate il ponte quattro", "it", "typed", "enemy", "crew"),
    B("sigilla i portelli e tienili chiusi", "it", "typed", "enemy", "crew"),
    B("dite al dottor Lindqvist di prepararsi ai feriti", "it", "typed", "enemy", "crew"),
    B("come sta l'equipaggio del brightwater", "it", "typed", "enemy", "crew"),
    B("Comunicazioni, cercate di parlare con il Brightwater.", "it", "spoken", "enemy", "crew"),
    B("Brightwater, qui l'Aquila. Mi ricevete?", "it", "spoken", "enemy", "external", hard=True),
    # ---- a bargain, said to the enemy in every register
    B("ti offro il trenta per cento del carico", "it", "typed", "enemy", "external"),
    B("hey ferryman lasciaci in pace o ti spedisco all'inferno", "it", "typed", "enemy", "external"),
    B("vael sei ancora li", "it", "typed", "enemy", "external"),
    B("quanti siete", "it", "typed", "enemy", "external", hard=True),
    B("cosa c'e nel vostro carico", "it", "typed", "enemy", "external"),
    B("Ferryman, non c'è bisogno che finisca male per nessuno dei due.", "it", "spoken", "enemy", "external"),
    B("Senta, Vael, parliamoci chiaro: lei non può vincere.", "it", "spoken", "enemy", "external"),
    B("Ehm, Ferryman, forse possiamo trovare un accordo.", "it", "spoken", "enemy", "external"),
    B("Le do la mia parola di capitano: nessuno verrà toccato.", "it", "spoken", "enemy", "external"),
    B("Se cede adesso, la lasceremo andare con le sue navi.", "it", "spoken", "enemy", "external"),
    B("Va bene, allora aspettiamo. Voss, non toccare il grilletto.", "it", "spoken", "enemy", "crew"),
    B("Allora, Serra, secondo lei ci sta mentendo?", "it", "spoken", "enemy", "crew"),
    B("Vael ci sta prendendo tempo, Voss. Continua a tenerla sotto tiro.", "it", "spoken", "enemy", "crew"),
    B("Comunicazioni, ditele che accetto le sue condizioni.", "it", "spoken", "enemy", "crew"),
    B("Senti Ferri, quanto manca per uscire dalla loro portata?", "it", "spoken", "enemy", "crew"),
    B("Ok, Tanaka, mettiamo il Cocytus sul grande schermo e vediamo cosa fa.", "it", "spoken", "enemy", "crew"),
    B("Nair, potresti dirmi se il Phlegethon sta ancora manovrando?", "it", "spoken", "enemy", "crew"),
    B("Ok Vael ti ascolto. Voss, tieni gli occhi aperti.", "it", "spoken", "enemy", "both", ext="ti ascolto", crew="tieni gli occhi aperti"),
    B("Ferri, virata a dritta. Ferryman, questa è la sua ultima occasione.", "it", "spoken", "enemy", "both", ext="ultima occasione", crew="virata a dritta"),
    # ---- an exchange going on
    B("quanto vuoi", "it", "typed", "live", "external"),
    B("e se rifiutassi", "it", "typed", "live", "external"),
    B("chi ti dice che non e una trappola", "it", "typed", "live", "external"),
    B("ma perche dovrei crederti", "it", "typed", "live", "external"),
    B("basta cosi", "it", "typed", "live", "external", hard=True),
    B("Serra, che ne pensi di questa offerta?", "it", "spoken", "live", "crew"),
    B("Voss, quanto ci mettono a entrare in raggio?", "it", "spoken", "live", "crew"),
    B("Comunicazioni, registrate questa conversazione.", "it", "spoken", "live", "crew"),
    B("chi e quello che ha appena parlato", "it", "typed", "live", "crew", hard=True),
    B("Sì, ho capito. Mi lasci il tempo di consultare i miei ufficiali.", "it", "spoken", "live", "external"),
    B("Sure, Ferryman. What exactly are you offering?", "en", "spoken", "live", "external"),
    B("no deal", "en", "typed", "live", "external"),
    B("and why should i trust you", "en", "typed", "live", "external"),
    B("tactical what do you make of that", "en", "typed", "live", "crew"),
    B("Nair, is she telling the truth?", "en", "spoken", "live", "crew"),
    # ---- English, typed and spoken, other angles
    B("prep the boarding party", "en", "typed", "enemy", "crew"),
    B("seal the deck", "en", "typed", "enemy", "crew"),
    B("get the doctor to the hangar", "en", "typed", "enemy", "crew"),
    B("how long until we reach the gate", "en", "typed", "enemy", "crew"),
    B("can the reactor take it", "en", "typed", "enemy", "crew"),
    B("dont let them get behind us", "en", "typed", "enemy", "crew"),
    B("what do we know about her ship", "en", "typed", "enemy", "crew"),
    B("Comms, hail the Brightwater and tell them to hold on.", "en", "spoken", "enemy", "crew"),
    B("Ops, how many of them are there?", "en", "spoken", "enemy", "crew"),
    B("Right, Serra, let's see if she's bluffing.", "en", "spoken", "enemy", "crew"),
    B("all right ferryman you win take the cargo", "en", "typed", "enemy", "external"),
    B("what will it take to make you leave", "en", "typed", "enemy", "external"),
    B("half the cargo and you go", "en", "typed", "enemy", "external"),
    B("this is your last chance vael", "en", "typed", "enemy", "external"),
    B("nobody has to die today ferryman", "en", "typed", "enemy", "external"),
    B("Captain Vael, I'd like to propose a truce.", "en", "spoken", "enemy", "external"),
    B("Ferryman, if you fire on the Brightwater, I will destroy you.", "en", "spoken", "enemy", "external"),
    B("You've made your point, Ferryman. Now let's end this.", "en", "spoken", "enemy", "external"),
    B("I'm listening, Vael. Voss, hold your fire.", "en", "spoken", "enemy", "both", ext="i'm listening", crew="hold your fire"),
    B("Tanaka, put her on screen. Ferryman, look at me when I talk to you.", "en", "spoken", "enemy", "both", ext="look at me", crew="put her on screen"),
    # ---- Spanish, French, German: other angles
    B("preparen el abordaje", "es", "typed", "enemy", "crew"),
    B("cuanto falta para llegar a la puerta", "es", "typed", "enemy", "crew"),
    B("Ferri, aléjanos de ellos.", "es", "spoken", "enemy", "crew"),
    B("Comunicaciones, llamen al Brightwater.", "es", "spoken", "enemy", "crew"),
    B("les doy la mitad de la carga y se van", "es", "typed", "enemy", "external"),
    B("Ferryman, usted sabe que no puede ganar.", "es", "spoken", "enemy", "external"),
    B("Vael, hablemos como personas razonables.", "es", "spoken", "enemy", "external"),
    B("préparez l'abordage", "fr", "typed", "enemy", "crew"),
    B("combien de temps avant la porte", "fr", "typed", "enemy", "crew"),
    B("Ferri, éloignez-nous d'eux.", "fr", "spoken", "enemy", "crew"),
    B("Comms, appelez le Brightwater.", "fr", "spoken", "enemy", "crew"),
    B("je vous donne la moitié de la cargaison", "fr", "typed", "enemy", "external"),
    B("Ferryman, vous savez que vous ne pouvez pas gagner.", "fr", "spoken", "enemy", "external"),
    B("Vael, parlons comme des gens raisonnables.", "fr", "spoken", "enemy", "external"),
    B("bereitet das Entern vor", "de", "typed", "enemy", "crew"),
    B("wie lange noch bis zum Tor", "de", "typed", "enemy", "crew"),
    B("Ferri, bringen Sie uns weg von ihnen.", "de", "spoken", "enemy", "crew"),
    B("Kommunikation, rufen Sie die Brightwater.", "de", "spoken", "enemy", "crew"),
    B("ich gebe euch die Hälfte der Ladung", "de", "typed", "enemy", "external"),
    B("Ferryman, Sie wissen, dass Sie nicht gewinnen können.", "de", "spoken", "enemy", "external"),
    B("Vael, reden wir wie vernünftige Menschen.", "de", "spoken", "enemy", "external"),
    # ---- the fleet channel and the allied ships
    B("Vigilant, coprite il nostro fianco destro.", "it", "spoken", "fleet", "external"),
    B("Praetorian, quanto siete lontani?", "it", "spoken", "fleet", "external"),
    B("Admiral Rourke, the Cocytus is breaking off. Request permission to pursue.", "en", "spoken", "fleet", "external"),
    B("ammiraglio ci serve un'evacuazione medica", "it", "typed", "fleet", "external"),
    B("Ferri, portaci accanto al Vigilant.", "it", "spoken", "fleet", "crew"),
    B("Voss, dammi i missili sul bersaglio dell'ammiraglio.", "it", "spoken", "fleet", "crew"),
    B("Comms, what is the fleet doing?", "en", "spoken", "fleet", "crew"),
    B("Understood, Admiral. Helm, follow the Praetorian.", "en", "spoken", "fleet_live", "both", ext="understood", crew="follow the praetorian"),
    B("ricevuto ammiraglio", "it", "typed", "fleet_live", "external"),
    B("chiedi all'ammiraglio cosa vuole che facciamo", "it", "typed", "fleet_live", "crew"),
    # ---- muted and no channel
    B("Ferryman, ultimo avvertimento.", "it", "spoken", "muted", "crew"),
    B("Vael, surrender now.", "en", "spoken", "muted", "crew"),
    B("Vael, ich warne Sie.", "de", "spoken", "muted", "crew"),
    B("cocytus mi ricevi", "it", "typed", "none", "crew"),
    B("Ferryman Vael, this is Captain of the Aquila. Respond.", "en", "spoken", "none", "crew"),
    B("Ferri, portaci in linea con il Cocytus e apri un canale.", "it", "spoken", "none", "crew"),
    # ---- looking at the screen or at an officer
    B("che cosa vuoi", "it", "typed", "enemy", "external", facing="viewscreen"),
    B("fermati", "it", "typed", "live", "external", facing="viewscreen"),
    B("scudi", "it", "typed", "enemy", "crew", facing="tactical"),
    B("piu piano", "it", "typed", "enemy", "crew", facing="helm"),
    B("come va", "it", "typed", "enemy", "crew", facing="engineering"),
]
