"""The router's blind test set: written after the rules were frozen (bench/router_set.py: DEV, PLAYTEST), never used to tune them.
Same format and channel states as the dev set. Measured once; whatever is fixed afterwards is reported as such."""
from __future__ import annotations

from .router_set import Item, _mk

T = _mk("test")

TEST: list[Item] = [
    # ---- Italian, typed: the Captain in the middle of a fight, channel open with the Cocytus
    T("punta il cocytus e tienilo sotto tiro", "it", "typed", "enemy", "crew"),
    T("spara al cocytus con tutto quello che hai", "it", "typed", "enemy", "crew"),
    T("che fanno adesso", "it", "typed", "enemy", "crew", hard=True),
    T("chi comanda quella nave", "it", "typed", "enemy", "crew", hard=True),
    T("dammi la situazione dei danni", "it", "typed", "enemy", "crew"),
    T("i motori tengono", "it", "typed", "enemy", "crew", hard=True),
    T("tienili a schermo e ingrandisci", "it", "typed", "enemy", "crew"),
    T("puntate sul phlegethon", "it", "typed", "enemy", "crew"),
    T("non sparare ancora", "it", "typed", "enemy", "crew"),
    T("sensori passivi e zitti tutti", "it", "typed", "enemy", "crew"),
    T("che distanza abbiamo dal gate", "it", "typed", "enemy", "crew"),
    T("preparate un tiro di missili", "it", "typed", "enemy", "crew"),
    T("i caccia tornino a bordo", "it", "typed", "enemy", "crew"),
    T("mettete a schermo la nostra flotta", "it", "typed", "enemy", "crew"),
    T("quanto scafo ci resta", "it", "typed", "enemy", "crew"),
    T("mostrami cosa c'e dietro di loro", "it", "typed", "enemy", "crew"),
    T("attiva i decoy", "it", "typed", "enemy", "crew"),
    T("voglio sapere quanti sono", "it", "typed", "enemy", "crew"),
    T("ritira i droni", "it", "typed", "enemy", "crew"),
    T("mandate un messaggio alla flotta", "it", "typed", "enemy", "crew"),
    T("manda tutto quello che hai sul cocytus", "it", "typed", "enemy", "crew"),
    T("ehi mi ricevete", "it", "typed", "enemy", "crew", hard=True),
    # ---- Italian, typed: addressed to the enemy
    T("ascolta cocytus non deve finire cosi", "it", "typed", "enemy", "external"),
    T("posso offrirvi un passaggio sicuro se vi ritirate", "it", "typed", "enemy", "external"),
    T("ritirate le vostre navi e vi lascio andare", "it", "typed", "enemy", "external"),
    T("lasciateci passare e nessuno si fara male", "it", "typed", "enemy", "external"),
    T("state indietro o apro il fuoco", "it", "typed", "enemy", "external"),
    T("sono il capitano dell'aquila e voi chi siete", "it", "typed", "enemy", "external"),
    T("tu chi sei", "it", "typed", "enemy", "external", hard=True),
    T("lei ha fatto una scelta sbagliata ferryman", "it", "typed", "enemy", "external"),
    T("vael pensaci bene", "it", "typed", "enemy", "external"),
    T("avete perso il vostro ammiraglio", "it", "typed", "enemy", "external", hard=True),
    T("non c'e nessun bisogno di morire oggi", "it", "typed", "enemy", "external", hard=True),
    T("archon solm sono pronto a parlare", "it", "typed", "enemy", "external"),
    T("cocytus disattivate i motori e preparatevi all'abbordaggio", "it", "typed", "enemy", "external"),
    # ---- Italian, spoken
    T("Ferryman Vael, mi riceve? Qui è il capitano dell'Aquila.", "it", "spoken", "enemy", "external"),
    T("Tattico, i missili sono pronti?", "it", "spoken", "enemy", "crew"),
    T("Sensori, il Cocytus è ancora l'unica nave ostile?", "it", "spoken", "enemy", "crew"),
    T("Un momento, Ferryman. Voss, dammi una soluzione di tiro sul Cocytus.", "it", "spoken", "enemy", "both", ext="momento",
      crew="soluzione di tiro"),
    T("Non voglio uccidere il suo equipaggio, Ferryman. Si ritiri e vivrà.", "it", "spoken", "enemy", "external"),
    T("Tanaka, metti il Cocytus sullo schermo principale.", "it", "spoken", "enemy", "crew"),
    T("Numero uno, che ne pensa dell'offerta di Vael?", "it", "spoken", "live", "crew"),
    T("Ferri, fai in modo di tenerli sempre di prua.", "it", "spoken", "enemy", "crew"),
    T("Le do la mia parola, Ferryman: nessuno sparerà se vi ritirate.", "it", "spoken", "live", "external"),
    T("Comunicazioni, riaprite il canale con la Praetorian.", "it", "spoken", "enemy", "crew"),
    T("Quanti missili hanno ancora, Nair?", "it", "spoken", "enemy", "crew"),
    T("Signori, prepariamoci al peggio.", "it", "spoken", "enemy", "crew"),
    T("Sarà una battaglia dura, ma ce la faremo.", "it", "spoken", "enemy", "crew", hard=True),
    # ---- Italian: exchange going on
    T("no grazie", "it", "typed", "live", "external"),
    T("state mentendo", "it", "typed", "live", "external"),
    T("che garanzie mi date", "it", "typed", "live", "external"),
    T("scudi a poppa", "it", "typed", "live", "crew"),
    T("basta cosi", "it", "typed", "live", "external", hard=True),
    T("ne parlo con i miei ufficiali", "it", "typed", "live", "external", hard=True),
    T("Sì, accetto. Fermate il fuoco.", "it", "spoken", "live", "external"),
    T("Tattico, sospendi il fuoco finché non te lo dico io.", "it", "spoken", "live", "crew"),
    # ---- no channel / muted
    T("Ferryman Vael, arrendetevi.", "it", "spoken", "none", "crew"),
    T("cocytus mi ricevi", "it", "typed", "none", "crew"),
    T("comunicazioni chiama il cocytus", "it", "typed", "none", "crew"),
    T("voi due mandate i droni", "it", "typed", "none", "crew"),
    T("Ferryman, mi ascolti, ritiratevi.", "it", "spoken", "muted", "crew"),
    T("ritiratevi subito", "it", "typed", "muted", "crew"),
    T("cosa fanno i cocytus", "it", "typed", "muted", "crew"),
    # ---- fleet channel
    T("ammiraglio siamo sotto attacco, chiediamo copertura", "it", "typed", "fleet", "external"),
    T("vigilant spostatevi a dritta", "it", "typed", "fleet", "external"),
    T("Praetorian, qui Aquila: come state messi con i missili?", "it", "spoken", "fleet", "external"),
    T("Rourke, ho bisogno di rinforzi adesso.", "it", "spoken", "fleet", "external"),
    T("Comunicazioni, che dice l'ammiraglio?", "it", "spoken", "fleet_live", "crew"),
    T("scudi a prua", "it", "typed", "fleet", "crew"),
    T("Grazie, ammiraglio. Terremo la linea.", "it", "spoken", "fleet_live", "external"),
    # ---- facing
    T("dammi tutta la spinta che hai", "it", "typed", "enemy", "crew", facing="engineering"),
    T("che intenzioni avete", "it", "typed", "live", "external", facing="viewscreen"),
    T("come stiamo messi", "it", "typed", "enemy", "crew", facing="ops"),
    # ---- English, typed
    T("target their engines", "en", "typed", "enemy", "crew"),
    T("keep them on the screen", "en", "typed", "enemy", "crew"),
    T("theyre turning follow them", "en", "typed", "enemy", "crew"),
    T("open fire", "en", "typed", "enemy", "crew"),
    T("cease fire", "en", "typed", "enemy", "crew", hard=True),
    T("how many ships do they have", "en", "typed", "enemy", "crew"),
    T("give me a full sweep", "en", "typed", "enemy", "crew"),
    T("bring the fighters home", "en", "typed", "enemy", "crew"),
    T("what are they doing", "en", "typed", "enemy", "crew", hard=True),
    T("vael are you still there", "en", "typed", "enemy", "external"),
    T("captain vael you are outgunned", "en", "typed", "enemy", "external"),
    T("cut your engines and prepare to be boarded", "en", "typed", "enemy", "external"),
    T("i can end this right now if you stand down", "en", "typed", "enemy", "external"),
    T("last warning cocytus", "en", "typed", "enemy", "external"),
    T("you have my word", "en", "typed", "live", "external"),
    T("not a chance", "en", "typed", "live", "external"),
    # ---- English, spoken
    T("Hold on, Vael. Voss, are the missiles ready?", "en", "spoken", "enemy", "both", ext="hold on", crew="missiles ready"),
    T("Nair, is there anything behind them?", "en", "spoken", "enemy", "crew"),
    T("Ferryman, this is your last chance to walk away.", "en", "spoken", "enemy", "external"),
    T("Ferri, keep the bow on the Cocytus.", "en", "spoken", "enemy", "crew"),
    T("Serra, you have the conn.", "en", "spoken", "enemy", "crew"),
    T("Thank you, Voss. That was a good shot.", "en", "spoken", "enemy", "crew"),
    T("Comms, get me the Praetorian.", "en", "spoken", "enemy", "crew"),
    T("Commander Vael, I'm prepared to accept a ceasefire on equal terms.", "en", "spoken", "enemy", "external"),
    T("We will not surrender, Ferryman. Not today.", "en", "spoken", "live", "external"),
    T("Fine, but my crew goes free.", "en", "spoken", "live", "external"),
    T("Admiral, this is the Aquila. We are engaged with three destroyers.", "en", "spoken", "fleet", "external"),
    T("Helm, evasive. Ops, reroute power to the forward shields.", "en", "spoken", "enemy", "crew"),
    T("All hands, brace for impact.", "en", "spoken", "enemy", "crew"),
    T("Ferryman Vael, this is the Aquila.", "en", "spoken", "none", "crew"),
    T("Ferryman, do you copy?", "en", "spoken", "muted", "crew"),
    # ---- Spanish
    T("dispara al cocytus", "es", "typed", "enemy", "crew"),
    T("cuantos enemigos quedan", "es", "typed", "enemy", "crew"),
    T("pon el cocytus en pantalla", "es", "typed", "enemy", "crew"),
    T("informe de danos", "es", "typed", "enemy", "crew"),
    T("ferryman escuchame bien", "es", "typed", "enemy", "external"),
    T("les daremos una oportunidad de retirarse", "es", "typed", "enemy", "external"),
    T("Ferri, mantén la proa hacia el Cocytus.", "es", "spoken", "enemy", "crew"),
    T("Ferryman Vael, aquí el capitán del Aquila. Detengan el fuego.", "es", "spoken", "enemy", "external"),
    T("Táctico, ¿los misiles están listos?", "es", "spoken", "enemy", "crew"),
    T("Le ofrezco una salida honorable, Ferryman.", "es", "spoken", "enemy", "external"),
    T("No confío en usted.", "es", "spoken", "live", "external"),
    # ---- French
    T("tirez sur le cocytus", "fr", "typed", "enemy", "crew"),
    T("combien d'ennemis restent ils", "fr", "typed", "enemy", "crew"),
    T("mettez le cocytus a l'ecran", "fr", "typed", "enemy", "crew"),
    T("ferryman ecoutez moi bien", "fr", "typed", "enemy", "external"),
    T("nous vous laissons une chance de partir", "fr", "typed", "enemy", "external", hard=True),
    T("Ferri, gardez la proue sur le Cocytus.", "fr", "spoken", "enemy", "crew"),
    T("Ferryman Vael, ici le capitaine de l'Aquila. Cessez le feu.", "fr", "spoken", "enemy", "external"),
    T("Tactique, les missiles sont-ils prêts ?", "fr", "spoken", "enemy", "crew"),
    T("Je vous offre une sortie honorable, Ferryman.", "fr", "spoken", "enemy", "external"),
    T("Je ne vous fais pas confiance.", "fr", "spoken", "live", "external"),
    # ---- German
    T("schiess auf die cocytus", "de", "typed", "enemy", "crew"),
    T("wie viele feinde sind noch da", "de", "typed", "enemy", "crew"),
    T("zeig die cocytus auf dem bildschirm", "de", "typed", "enemy", "crew"),
    T("ferryman hoeren sie mir zu", "de", "typed", "enemy", "external"),
    T("wir geben euch eine chance abzuziehen", "de", "typed", "enemy", "external", hard=True),
    T("Ferri, halten Sie den Bug auf die Cocytus.", "de", "spoken", "enemy", "crew"),
    T("Ferryman Vael, hier spricht die Aquila. Stellen Sie das Feuer ein.", "de", "spoken", "enemy", "external"),
    T("Taktik, sind die Raketen bereit?", "de", "spoken", "enemy", "crew"),
    T("Ich biete Ihnen einen ehrenvollen Rückzug an, Ferryman.", "de", "spoken", "enemy", "external"),
    T("Ich vertraue Ihnen nicht.", "de", "spoken", "live", "external"),
]
