#!/usr/bin/env python3
"""Per-ship data of the war's visual effects (Source/ASTRA/AstraWarFX*.cpp), written as a C++ table the game compiles in:
the drive bells (where the engine plumes start, from data/war/fx_nozzles.json, made by tools/art/war_fx_nozzles.py) and, for the
capital ships that break up, the three section pieces (pivot, extent along x) and the cut faces (where the pieces were cut: centre,
size and normal of each face, from the ships' manifest, art/export/ships_v3/manifest.json).

  python3 tools/art/war_fx_data.py [--manifest art/export/ships_v3/manifest.json] [--out Source/ASTRA/AstraWarFXData.inl]

The manifest is not in git (ARTE-NAVI's FBX export); the table that comes out of it is, so this runs only when a hull changes.
Frame: the ship's own (x forward, y starboard, z up), metres, the mesh's origin at the origin.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SECTIONS = ("Bow", "Mid", "Stern")


def f(x: float) -> str:
    """A C++ float literal ("388.0f", "-0.5f": a literal needs its decimal point)."""
    s = f"{x:.3f}".rstrip("0")
    if s.endswith("."):
        s += "0"
    if s in ("-0.0", "-0."):
        s = "0.0"
    return s + "f"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", default=str(ROOT / "art/export/ships_v3/manifest.json"))
    ap.add_argument("--nozzles", default=str(ROOT / "data/war/fx_nozzles.json"))
    ap.add_argument("--out", default=str(ROOT / "Source/ASTRA/AstraWarFXData.inl"))
    a = ap.parse_args()
    man = json.loads(Path(a.manifest).read_text(encoding="utf-8"))["meshes"]
    noz = json.loads(Path(a.nozzles).read_text(encoding="utf-8"))["ships"]
    names = sorted(set(noz) | {n for n, e in man.items() if e.get("class") in ("capital", "craft")})
    lines = [
        "// ASTRA — per-ship data of the war's visual effects (drive bells, break-up pieces and their cut faces).",
        "// GENERATED by tools/art/war_fx_data.py from data/war/fx_nozzles.json and the ships' manifest: do not edit by hand.",
        "// Frame: the ship's own (x forward, y starboard, z up), metres, the mesh's origin at the origin.",
        "",
        "{",
    ]
    for name in names:
        e = man.get(name, {})
        bells = noz.get(name, {}).get("main", [])
        lines.append(f"\t// {name}")
        lines.append("\t{")
        lines.append(f'\t\tTEXT("{name}"),')
        # the drive bells: throat centre (x, y, z), throat radius, the lip's distance from the throat down the exhaust
        b = ", ".join("{" + ", ".join(f(v) for v in (*bl["pos"], bl["r"], bl["lip"])) + "}" for bl in bells[:8])
        lines.append(f"\t\t{len(bells[:8])}, {{{b}}},")
        # the pieces and the faces they were cut with
        pieces = []
        for k, sec in enumerate(SECTIONS):
            p = man.get(f"{name}_Sec{sec}")
            pieces.append(p)
        has = e.get("class") == "capital" and all(pieces) and e.get("cut_faces")
        if has:
            pv = ", ".join("{" + ", ".join(f(v) for v in (*p["pivot_m"], p["x_range_m"][0], p["x_range_m"][1])) + "}" for p in pieces)
            faces = []
            for fc in e["cut_faces"][:4]:
                faces.append("{" + ", ".join([str(int(fc["section"])), f(fc["x"]), f(fc["normal"][0]), f(fc["center"][1]), f(fc["center"][2]),
                                              f(0.5 * (fc["y"][1] - fc["y"][0])), f(0.5 * (fc["z"][1] - fc["z"][0]))]) + "}")
            lines.append(f"\t\ttrue, {{{pv}}},")
            lines.append(f"\t\t{len(faces)}, {{{', '.join(faces)}}},")
        else:
            lines.append("\t\tfalse, {{}, {}, {}},")
            lines.append("\t\t0, {},")
        lines.append("\t},")
    lines.append("}")
    Path(a.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(names)} ships -> {a.out}")


if __name__ == "__main__":
    main()
