#!/usr/bin/env python3
"""Per-ship data of the war's visual effects (Source/ASTRA/AstraWarFX*.cpp), written as a C++ table the game compiles in:
the drive bells (where the engine plumes start, from data/war/fx_nozzles.json, made by tools/art/war_fx_nozzles.py) and, for the
capital ships that break up, the three section pieces (pivot, extent along x) and the cut faces (where the pieces were cut: centre,
size and normal of each face, from the ships' manifest, art/export/ships_v3/manifest.json).

  python3 tools/art/war_fx_data.py [--manifest art/export/ships_v3/manifest.json] [--out Source/ASTRA/AstraWarFXData.inl]
                                   [--surface data/war/fx_hull_surface.json] [--surface-out Source/ASTRA/AstraWarFXSurface.inl]

The second table is the skin of each capital hull seen from the six faces of its box (tools/art/war_fx_hull_surface.py, Blender: data/war/fx_hull_surface.json), so that a blow, a fire, a glow
or a scar is put on the hull and not on the plane of the box (AstraWarFXHull.cpp: SnapToHull). It is written when its json is there.

The manifest is not in git (ARTE-NAVI's FBX export); the table that comes out of it is, so this runs only when a hull changes.
Frame: the ship's own (x forward, y starboard, z up), metres, the mesh's origin at the origin.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SECTIONS = ("Bow", "Mid", "Stern")


def f(x: float) -> str:
    """A C++ float literal ("388.0f", "-0.5f": a literal needs its decimal point)."""
    s = f"{x:.3f}".rstrip("0")
    if s.endswith("."):
        s += "0"
    if s in ("-0.0", "-0."):
        s = "0.0"
    return s + "f"


SURF_GRID = (48, 16, 16)       # cells along the ship, across it, up it: AstraWarFXHull.cpp (SurfNx, SurfNy, SurfNz) says the same


def write_surface(src: Path, out: Path, keep: set) -> None:
    """Source/ASTRA/AstraWarFXSurface.inl from data/war/fx_hull_surface.json: for each capital hull its bounds and the six grids of the skin (dm, int16)."""
    ships = json.loads(src.read_text(encoding="utf-8"))["ships"]
    lines = [
        "// ASTRA — the skin of each hull seen from the six faces of its box (war visual effects: where a blow, a fire, a glow, a scar goes).",
        "// GENERATED by tools/art/war_fx_data.py from data/war/fx_hull_surface.json (tools/art/war_fx_hull_surface.py, Blender): do not edit by hand.",
        "// Per ship: its bounds (x0 x1 y0 y1 z0 z1, m) and the grids, decimetres, the ship's frame (x forward, y starboard, z up), the mesh's origin at the origin:",
        "// top and bottom over (x, y) -> z; starboard and port over (x, z) -> y; bow and stern over (y, z) -> x.",
        "",
        "{",
    ]
    n = 0
    for name in sorted(ships):
        if name not in keep:
            continue
        sh = ships[name]
        assert (sh["nx"], sh["ny"], sh["nz"]) == SURF_GRID, (name, sh["nx"], sh["ny"], sh["nz"])
        lines.append(f"\t// {name}")
        lines.append("\t{")
        lines.append(f'\t\tTEXT("{name}"),')
        lines.append("\t\t{" + ", ".join(f(v) for v in sh["bounds_m"]) + "},")
        for key in ("top", "bottom", "starboard", "port", "bow", "stern"):
            v = [int(round(c / 10.0)) for c in sh[key]]                  # decimetres: a bow 550 m from the origin is 5500, an int16 holds 3276 m
            assert abs(max(v)) < 32000 and abs(min(v)) < 32000, (name, key)
            rows = ["\t\t\t" + ", ".join(str(int(x)) for x in v[i:i + 16]) for i in range(0, len(v), 16)]
            lines.append("\t\t{\n" + ",\n".join(rows) + "\n\t\t},")
        lines.append("\t},")
        n += 1
    lines.append("}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{n} hulls -> {out}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", default=str(ROOT / "art/export/ships_v3/manifest.json"))
    ap.add_argument("--nozzles", default=str(ROOT / "data/war/fx_nozzles.json"))
    ap.add_argument("--out", default=str(ROOT / "Source/ASTRA/AstraWarFXData.inl"))
    ap.add_argument("--surface", default=str(ROOT / "data/war/fx_hull_surface.json"))
    ap.add_argument("--surface-out", default=str(ROOT / "Source/ASTRA/AstraWarFXSurface.inl"))
    a = ap.parse_args()
    man = json.loads(Path(a.manifest).read_text(encoding="utf-8"))["meshes"]
    noz = json.loads(Path(a.nozzles).read_text(encoding="utf-8"))["ships"]
    names = sorted(set(noz) | {n for n, e in man.items() if e.get("class") in ("capital", "craft")})
    lines = [
        "// ASTRA — per-ship data of the war's visual effects (drive bells, break-up pieces and their cut faces).",
        "// GENERATED by tools/art/war_fx_data.py from data/war/fx_nozzles.json and the ships' manifest: do not edit by hand.",
        "// Frame: the ship's own (x forward, y starboard, z up), metres, the mesh's origin at the origin.",
        "",
        "{",
    ]
    for name in names:
        e = man.get(name, {})
        bells = noz.get(name, {}).get("main", [])
        lines.append(f"\t// {name}")
        lines.append("\t{")
        lines.append(f'\t\tTEXT("{name}"),')
        # the drive bells: throat centre (x, y, z), throat radius, the lip's distance from the throat down the exhaust
        b = ", ".join("{" + ", ".join(f(v) for v in (*bl["pos"], bl["r"], bl["lip"])) + "}" for bl in bells[:8])
        lines.append(f"\t\t{len(bells[:8])}, {{{b}}},")
        # the pieces and the faces they were cut with
        pieces = []
        for k, sec in enumerate(SECTIONS):
            p = man.get(f"{name}_Sec{sec}")
            pieces.append(p)
        has = e.get("class") == "capital" and all(pieces) and e.get("cut_faces")
        if has:
            pv = ", ".join("{" + ", ".join(f(v) for v in (*p["pivot_m"], p["x_range_m"][0], p["x_range_m"][1])) + "}" for p in pieces)
            faces = []
            for fc in e["cut_faces"][:4]:
                faces.append("{" + ", ".join([str(int(fc["section"])), f(fc["x"]), f(fc["normal"][0]), f(fc["center"][1]), f(fc["center"][2]),
                                              f(0.5 * (fc["y"][1] - fc["y"][0])), f(0.5 * (fc["z"][1] - fc["z"][0]))]) + "}")
            lines.append(f"\t\ttrue, {{{pv}}},")
            lines.append(f"\t\t{len(faces)}, {{{', '.join(faces)}}},")
        else:
            lines.append("\t\tfalse, {{}, {}, {}},")
            lines.append("\t\t0, {},")
        lines.append("\t},")
    lines.append("}")
    Path(a.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(names)} ships -> {a.out}")
    if Path(a.surface).exists():
        write_surface(Path(a.surface), Path(a.surface_out), set(n for n, e in man.items() if e.get("class") == "capital") | {"SM_STATION_ASTRA_Watch"})


if __name__ == "__main__":
    main()
