// ASTRA — FLOTTA-VIVA: the plan of a class of ship, as the war reads it (docs/FLOTTA-VIVA.md).
//
// Every ship of the war has an interior: its class's plan (data/ship/plans/<class>.json, in the format of the Aquila's plan and a superset of it,
// generated by art/blender/ship_class_plans.py) read by the same map the Aquila's damage model stands on (AstraDamageMap), plus what the war needs
// of a ship's people: how many are aboard, where they stand at action stations (the garrison), which of them are the officers who matter (the
// billets), where the damage-control parties muster, which rooms a boarding party goes for (the objectives), where the boarding hatches are.
//
// Plain data over the plan (no actors, no world); loaded once per class and shared by every ship of it. A class with no plan file has no interior
// and its ships stay as they were (the war's section model alone).

#pragma once

#include "CoreMinimal.h"
#include "AstraDamageMap.h"

/** A named post of a ship's chain of command: the officer who stands where. */
struct FFleetBillet
{
	FName Role;                       // captain, executive_officer, tactical_officer, chief_engineer, medical_officer, security_chief, flight_officer
	FString Rank;                     // "Captain", "Ferryman": the class's own word for it
	int32 Line = 0;                   // the order the command passes in (1: the captain)
	int32 Comp = INDEX_NONE;          // the room they hold at action stations
	FVector PostCm = FVector::ZeroVector;    // where they stand (plan cm)
};

/** Where some of the crew stand at action stations. */
struct FFleetGarrison
{
	int32 Comp = INDEX_NONE;
	int32 N = 0;
	FName Role;                       // bridge, control, gunnery, magazine, engineering, damage_control, medical, flight, sensors, marines, marines_dock, reserve
};

/** A damage-control party: where it musters and how many it is. */
struct FFleetParty
{
	int32 Home = INDEX_NONE;
	int32 Size = 4;
	TArray<float> TravelS;            // seconds from its home to each compartment of the plan (a run, by the doors and the stairs)
};

/** A boarding hatch on the skin (ABBORDAGGI reads these; the interior only lists them). */
struct FFleetDock
{
	FName Id;
	int32 Comp = INDEX_NONE;
	FName Face;
	FVector PosM = FVector::ZeroVector, NormalM = FVector::ForwardVector;
	int32 Deck = 0;
	FName Kind;
};

struct FFleetClassPlan
{
	FName Key;
	FString Style;                    // "astra" | "mandate" | "guild"
	FString Label;
	TSharedPtr<FAstraDamageMap> Map;
	int32 Complement = 0, Marines = 0, Officers = 0;
	TMap<FName, FString> Ranks;       // role -> the class's word for it
	TArray<FFleetBillet> Billets;
	TArray<FFleetGarrison> Garrison;
	TArray<FFleetParty> Parties;
	TArray<FFleetDock> Docks;
	TMap<FName, int32> Objectives;    // bridge, engineering, captain, armory, medbay, brig, comms, hangar ... -> compartment
	int32 DcCentral = INDEX_NONE;
	float CutBowCm = 0.f, CutSternCm = 0.f;   // the class's two cut planes in the plan's frame (cm): the war's sections are bow beyond the first, stern beyond the second
	bool bMandate = false;

	int32 Objective(const TCHAR* Name) const { const int32* I = Objectives.Find(FName(Name)); return I ? *I : INDEX_NONE; }
};

/** The plans of the classes, loaded once and shared. Thread-safe. */
class ASTRA_API FAstraFleetPlans
{
public:
	/** The plan of a class (the key of data/war/classes.json); null when it has none. Loads it on first use (a worker may have started it: Prefetch). */
	static TSharedPtr<const FFleetClassPlan> Find(FName ClassKey);
	/** Starts loading a class's plan on a worker: a ship of the class is about to be hit. */
	static void Prefetch(FName ClassKey);
	/** Where a class's plan is read from (Content/ASTRA/Data/plans first: packaged as a loose file; then the repository's), "" when neither exists. */
	static FString PathFor(FName ClassKey);
	/** Reads a plan from a file without caching it (the benches, the tests). */
	static TSharedPtr<FFleetClassPlan> LoadFile(FName ClassKey, const FString& Path, FString& OutError);
	/** Forgets what was loaded (the benches that change a plan). */
	static void Clear();
};
